name = "StochasticCashFlow"
uuid = "99d3b20c-44be-4410-b145-f748db8e568f"
authors = ["Antonello Lobianco <antonello@lobianco.org>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Distributions = "0.25"
LinearAlgebra = "1.6"
julia = "1.6"
